blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/ricokahler/onshape-cadscript/security/advisories/new
    about: Report security issues privately.
